apiVersion: v1
kind: Namespace
metadata:
  name: gravitee
---
apiVersion: v1
kind: Service
metadata:
  name: gravitee-svc
  namespace: gravitee
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32100
    protocol: TCP
    name: management-ui
  - port: 8082
    targetPort: 8082
    nodePort: 32102
    protocol: TCP
    name: gateway
  - port: 8083
    targetPort: 8083
    nodePort: 32105
    protocol: TCP
    name: management-api
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: elasticsearch  
  selector:
    app: gravitee
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: gravitee
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee
  namespace: gravitee
spec:
  selector:
    matchLabels:
      app: gravitee
  replicas: 1
  template:
    metadata:
      labels:
        app: gravitee
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.31.0
        imagePullPolicy: Always
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.monitoring.enabled
              value: "false"
            - name: http.host
              value: "0.0.0.0"
            - name: transport.host
              value: "0.0.0.0"
            - name: cluster.name
              value: elasticsearch
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              protocol: TCP
        - name: mongo-db
          image: mongo:3.4.22-xenial
          env:
            - name: clover.datasource.type
              value: JDBC
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: "/data/db"
              name: mongodb-storage    
        - name: gateway
          image: graviteeio/gateway:1.28.1
          env:
            - name: gravitee_management_mongodb_uri
              value: "mongodb://gravitee-svc:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_ratelimit_mongodb_uri
              value: "mongodb://gravitee-svc:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_reporters_elasticsearch_endpoints_0
              value: "http://gravitee-svc:9200"
          ports:
            - containerPort: 8082
              protocol: TCP
        - name: management-api
          image: graviteeio/management-api:1.28.1
          env:
            - name: gravitee_management_mongodb_uri
              value: "mongodb://gravitee-svc:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_analytics_elasticsearch_endpoints_0
              value: "http://gravitee-svc:9200"
            - name: gravitee_swagger_scheme
              value: "http"  
          ports:
            - containerPort: 8083
              protocol: TCP
        - name: management-ui
          image: graviteeio/management-ui:1.28.1
          env:
            - name: MGMT_API_URL
              value: http://virt-oberon:32105/management/
          ports:
            - containerPort: 80
              protocol: TCP
      volumes: 
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc        