---
swagger: "2.0"
info:
  title: "CloverDX Data Services"
  description: "CloverDX Data Services"
  version: "1.0.0"
host: "virt-oberon:32381"
schemes: ["https"]
basePath: "/clover/data-service"
tags:
- name: "examples"
  externalDocs:
    description: "Find out more"
    url: "http://cloverdx.com"
paths:
  /echo/{message}:
    get:
      tags:
      - "examples"
      summary: ""
      description: ""
      operationId: "/echo/{message}_GET"
      consumes:
      - "plain/text"
      produces:
      - "custom"
      parameters:
      - in: "path"
        name: "message"
        required: true
        type: "string"
      - in: "header"
        name: "X-Clover-Save-Run-Record"
        type: "string"
        enum: "true"
        default: "true"
      responses:
        200:
          description: ""
        400:
          description: "Request validation failed"
        500:
          description: "Job failed"
  /kamil/{message}:
    get:
      tags:
      - "examples"
      summary: ""
      description: ""
      operationId: "/kamil/{message}_GET"
      consumes:
      - "plain/text"
      produces:
      - "custom"
      parameters:
      - in: "path"
        name: "message"
        required: true
        type: "string"
      - in: "header"
        name: "X-Clover-Save-Run-Record"
        type: "string"
        enum: "true"
        default: "true"
      responses:
        200:
          description: ""
        400:
          description: "Request validation failed"
        500:
          description: "Job failed"
