apiVersion: v1
kind: Service
metadata:
  name: gravitee-am-gateway-svc
spec:
  type: NodePort
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    name: gravitee-am-gateway
  selector:
    app: gravitee-am-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee-am-gateway
spec:
  selector:
    matchLabels:
      app: gravitee-am-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gravitee-am-gateway
    spec:
      containers:
        - name: gravitee-am-gateway
          image: graviteeio/am-gateway:2.8
          env:
            - name: gravitee_management_mongodb_uri
              value: "mongodb://mongodb-svc:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_oauth2_mongodb_uri
              value: "mongodb://mongodb-svc:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
          ports:
            - containerPort: 8092
              protocol: TCP
