apiVersion: v1
kind: Service
metadata:
  name: gravitee-management-ui-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: management-ui
  selector:
    app: gravitee-management-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee-management-ui
spec:
  selector:
    matchLabels:
      app: gravitee-management-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: gravitee-management-ui
    spec:
      containers:
        - name: management-ui
          image: graviteeio/management-ui:1.28.1
          env:
            - name: MGMT_API_URL
              value: "http://${KUBERNETES_HOST}:${MGMT_API_PORT}/management/"
          ports:
            - containerPort: 80
              protocol: TCP
