apiVersion: v1
kind: Service
metadata:
  name: gravitee-am-management-api-svc
spec:
  type: NodePort
  ports:
  - port: 8093
    targetPort: 8093
    protocol: TCP
    name: gravitee-am-management-api
  selector:
    app: gravitee-am-management-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee-am-management-api
spec:
  selector:
    matchLabels:
      app: gravitee-am-management-api
  replicas: 1
  template:
    metadata:
      labels:
        app: gravitee-am-management-api
    spec:
      containers:
        - name: am-management-api
          image: graviteeio/am-management-api:2.8
          env:
            - name: gravitee_management_mongodb_uri
              value: "mongodb://mongodb-svc:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_oauth2_mongodb_uri
              value: "mongodb://mongodb-svc:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
          ports:
            - containerPort: 8093
              protocol: TCP
