apiVersion: v1
kind: Service
metadata:
  name: gravitee-gateway-svc
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    ${GRAVITEE_GATEWAY_NODE_PORT}
    protocol: TCP
    name: gateway
  selector:
    app: gravitee-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee-gateway
spec:
  selector:
    matchLabels:
      app: gravitee-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gravitee-gateway
    spec:
      containers:
        - name: gateway
          image: graviteeio/gateway:1.28.1
          env:
            - name: gravitee_management_mongodb_uri
              value: "mongodb://mongodb-svc:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_ratelimit_mongodb_uri
              value: "mongodb://mongodb-svc:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_reporters_elasticsearch_endpoints_0
              value: "http://elasticsearch-svc:9200"
          ports:
            - containerPort: 8082
              protocol: TCP
