apiVersion: v1
kind: Service
metadata:
  name: gravitee-management-api-svc
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: gravitee-management-api
  selector:
    app: gravitee-management-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee-management-api
spec:
  selector:
    matchLabels:
      app: gravitee-management-api
  replicas: 1
  template:
    metadata:
      labels:
        app: gravitee-management-api
    spec:
      containers:
        - name: management-api
          image: graviteeio/management-api:1.28.1
          livenessProbe:
            httpGet:
              path: /management/apis
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 10
          env:
            - name: gravitee_management_mongodb_uri
              value: "mongodb://mongodb-svc:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
            - name: gravitee_analytics_elasticsearch_endpoints_0
              value: "http://elasticsearch-svc:9200"
          ports:
            - containerPort: 8083
              protocol: TCP
