apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
spec:
  template:
    metadata:
      name: init-job
    spec:
      volumes:
      - name: gravitee-config-volume
        configMap:
          name: gravitee-apis
          defaultMode: 0500
      restartPolicy: Never
      containers:
      - name: init-job
        image: bash:5.0
        volumeMounts:
          - mountPath: /config
            name: gravitee-config-volume
        command:
        - /bin/sh
        - -c
        - /config/init.sh
