apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongodb-pvc
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi 
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
        - name: mongo-db
          image: mongo:3.4.22-xenial
          env:
            - name: clover.datasource.type
              value: JDBC
          ports:
            - containerPort: 27017
              protocol: TCP
      #    volumeMounts:
      #      - mountPath: "/data/db"
      #        name: mongodb-storage    
      #volumes: 
      #  - name: mongodb-storage
      #    persistentVolumeClaim:
      #      claimName: mongodb-pvc        